### ISSUE TITLE
make use of nth-child

### ISSUE THREAD

**Issue by dakira** [ubuntu-on-reddit/redditstyle#1]
Stuff like this to make comments use alternating backgrounds should not be necessary:

``` css
.res-nightmode.res-commentBoxes .comments-page .comment .comment,
.res-nightmode.res-commentBoxes .comments-page .comment .comment .comment .comment,
.res-nightmode.res-commentBoxes .comments-page .comment .comment .comment .comment .comment .comment,
.res-nightmode.res-commentBoxes .comments-page .comment .comment .comment .comment .comment .comment .comment .comment,
.res-nightmode.res-commentBoxes .comments-page .comment .comment .comment .comment .comment .comment .comment .comment .comment .comment
{
    background-color:#292929!important;
}
```

There is the [:nth-child](https://css-tricks.com/almanac/selectors/n/nth-child/) selector for that.
